Upgrade `rustls` & `fluvio-async-tls`
infinyon/future-aio pull request #154
Opened 2022-06-15 08:14 UTC by heilhead

Fixes https://github.com/infinyon/future-aio/issues/125

This upgrades `rustls` to `0.20.6`.

Comes with breaking changes to `rust_tls::builder::ConnectorBuilder` and `rust_tls::builder::AcceptorBuilder`, which now follow the builder stages pattern from the `rustls` config builder.

Note: I wasn't able to verify changes with the tests from `rust_tls` module, since `certs/test-certs` are gitignored and I don't have access to the required certificates/keys.

Note: Requires https://github.com/infinyon/fluvio-async-tls/pull/3 to be merged and published first, so that we can update the dependency in this crate.

2022-06-16 23:09 UTC, morenol requested changes
nice work!

Could you bump version in `Cargo.toml`?

2022-06-17 08:45 UTC, heilhead commented
@morenol Which version should I set, `0.3.19` or `0.4.0`? There are some minor breaking changes, so I'm not sure how you guys would version it.

2022-06-20 21:02 UTC, sehz commented
@morenol can you respond to this?

2022-06-20 21:14 UTC, morenol commented
> @morenol Which version should I set, `0.3.19` or `0.4.0`? There are some minor breaking changes, so I'm not sure how you guys would version it.

I whink that we should update to `0.4.0` mostly due to the changes in `ConnectorBuilder` and `AcceptorBuilder`

2022-06-21 18:42 UTC, heilhead commented
@morenol I've just updated `fluvio-async-tls` to `0.3.0` (which includes https://github.com/infinyon/fluvio-async-tls/pull/3).

This PR is now ready for merge.

2022-06-21 20:37 UTC, sehz approved these changes
Nice job!

2022-06-21 20:37 UTC, sehz commented
bors r+

2022-06-21 20:50 UTC, closed without merging